package com.google.android.gms.internal.mlkit_vision_text_common;

import androidx.appcompat.app.AppCompatDelegate;
import androidx.media3.extractor.metadata.dvbsi.AppInfoTableDecoder;
import androidx.media3.extractor.ts.TsExtractor;
import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import io.flutter.plugins.firebase.analytics.Constants;
import java.io.IOException;
import kotlinx.coroutines.scheduling.WorkQueueKt;

/* compiled from: com.google.android.gms:play-services-mlkit-text-recognition-common@@19.1.0 */
/* loaded from: classes3.dex */
final class zzio implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzio zza = new zzio();
    private static final FieldDescriptor zzaA;
    private static final FieldDescriptor zzaB;
    private static final FieldDescriptor zzaC;
    private static final FieldDescriptor zzaD;
    private static final FieldDescriptor zzaE;
    private static final FieldDescriptor zzaF;
    private static final FieldDescriptor zzaG;
    private static final FieldDescriptor zzaH;
    private static final FieldDescriptor zzaI;
    private static final FieldDescriptor zzaJ;
    private static final FieldDescriptor zzaK;
    private static final FieldDescriptor zzaL;
    private static final FieldDescriptor zzaM;
    private static final FieldDescriptor zzaN;
    private static final FieldDescriptor zzaO;
    private static final FieldDescriptor zzaP;
    private static final FieldDescriptor zzaQ;
    private static final FieldDescriptor zzaR;
    private static final FieldDescriptor zzaS;
    private static final FieldDescriptor zzaT;
    private static final FieldDescriptor zzaU;
    private static final FieldDescriptor zzaV;
    private static final FieldDescriptor zzaW;
    private static final FieldDescriptor zzaX;
    private static final FieldDescriptor zzaY;
    private static final FieldDescriptor zzaZ;
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzap;
    private static final FieldDescriptor zzaq;
    private static final FieldDescriptor zzar;
    private static final FieldDescriptor zzas;
    private static final FieldDescriptor zzat;
    private static final FieldDescriptor zzau;
    private static final FieldDescriptor zzav;
    private static final FieldDescriptor zzaw;
    private static final FieldDescriptor zzax;
    private static final FieldDescriptor zzay;
    private static final FieldDescriptor zzaz;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzba;
    private static final FieldDescriptor zzbb;
    private static final FieldDescriptor zzbc;
    private static final FieldDescriptor zzbd;
    private static final FieldDescriptor zzbe;
    private static final FieldDescriptor zzbf;
    private static final FieldDescriptor zzbg;
    private static final FieldDescriptor zzbh;
    private static final FieldDescriptor zzbi;
    private static final FieldDescriptor zzbj;
    private static final FieldDescriptor zzbk;
    private static final FieldDescriptor zzbl;
    private static final FieldDescriptor zzbm;
    private static final FieldDescriptor zzbn;
    private static final FieldDescriptor zzbo;
    private static final FieldDescriptor zzbp;
    private static final FieldDescriptor zzbq;
    private static final FieldDescriptor zzbr;
    private static final FieldDescriptor zzbs;
    private static final FieldDescriptor zzbt;
    private static final FieldDescriptor zzbu;
    private static final FieldDescriptor zzbv;
    private static final FieldDescriptor zzbw;
    private static final FieldDescriptor zzbx;
    private static final FieldDescriptor zzby;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzct zzctVar = new zzct();
        zzctVar.zza(1);
        zzb = builder.withProperty(zzctVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder(Constants.EVENT_NAME);
        zzct zzctVar2 = new zzct();
        zzctVar2.zza(2);
        zzc = builder2.withProperty(zzctVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzct zzctVar3 = new zzct();
        zzctVar3.zza(37);
        zzd = builder3.withProperty(zzctVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzct zzctVar4 = new zzct();
        zzctVar4.zza(61);
        zze = builder4.withProperty(zzctVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzct zzctVar5 = new zzct();
        zzctVar5.zza(3);
        zzf = builder5.withProperty(zzctVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzct zzctVar6 = new zzct();
        zzctVar6.zza(20);
        zzg = builder6.withProperty(zzctVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzct zzctVar7 = new zzct();
        zzctVar7.zza(4);
        zzh = builder7.withProperty(zzctVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzct zzctVar8 = new zzct();
        zzctVar8.zza(29);
        zzi = builder8.withProperty(zzctVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzct zzctVar9 = new zzct();
        zzctVar9.zza(5);
        zzj = builder9.withProperty(zzctVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzct zzctVar10 = new zzct();
        zzctVar10.zza(59);
        zzk = builder10.withProperty(zzctVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzct zzctVar11 = new zzct();
        zzctVar11.zza(6);
        zzl = builder11.withProperty(zzctVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzct zzctVar12 = new zzct();
        zzctVar12.zza(79);
        zzm = builder12.withProperty(zzctVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzct zzctVar13 = new zzct();
        zzctVar13.zza(7);
        zzn = builder13.withProperty(zzctVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzct zzctVar14 = new zzct();
        zzctVar14.zza(58);
        zzo = builder14.withProperty(zzctVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzct zzctVar15 = new zzct();
        zzctVar15.zza(48);
        zzp = builder15.withProperty(zzctVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzct zzctVar16 = new zzct();
        zzctVar16.zza(49);
        zzq = builder16.withProperty(zzctVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzct zzctVar17 = new zzct();
        zzctVar17.zza(18);
        zzr = builder17.withProperty(zzctVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzct zzctVar18 = new zzct();
        zzctVar18.zza(26);
        zzs = builder18.withProperty(zzctVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzct zzctVar19 = new zzct();
        zzctVar19.zza(27);
        zzt = builder19.withProperty(zzctVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzct zzctVar20 = new zzct();
        zzctVar20.zza(28);
        zzu = builder20.withProperty(zzctVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzct zzctVar21 = new zzct();
        zzctVar21.zza(44);
        zzv = builder21.withProperty(zzctVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzct zzctVar22 = new zzct();
        zzctVar22.zza(45);
        zzw = builder22.withProperty(zzctVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzct zzctVar23 = new zzct();
        zzctVar23.zza(19);
        zzx = builder23.withProperty(zzctVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzct zzctVar24 = new zzct();
        zzctVar24.zza(21);
        zzy = builder24.withProperty(zzctVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzct zzctVar25 = new zzct();
        zzctVar25.zza(22);
        zzz = builder25.withProperty(zzctVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzct zzctVar26 = new zzct();
        zzctVar26.zza(8);
        zzA = builder26.withProperty(zzctVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzct zzctVar27 = new zzct();
        zzctVar27.zza(9);
        zzB = builder27.withProperty(zzctVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzct zzctVar28 = new zzct();
        zzctVar28.zza(10);
        zzC = builder28.withProperty(zzctVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzct zzctVar29 = new zzct();
        zzctVar29.zza(11);
        zzD = builder29.withProperty(zzctVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzct zzctVar30 = new zzct();
        zzctVar30.zza(12);
        zzE = builder30.withProperty(zzctVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzct zzctVar31 = new zzct();
        zzctVar31.zza(13);
        zzF = builder31.withProperty(zzctVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzct zzctVar32 = new zzct();
        zzctVar32.zza(14);
        zzG = builder32.withProperty(zzctVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzct zzctVar33 = new zzct();
        zzctVar33.zza(15);
        zzH = builder33.withProperty(zzctVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzct zzctVar34 = new zzct();
        zzctVar34.zza(16);
        zzI = builder34.withProperty(zzctVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzct zzctVar35 = new zzct();
        zzctVar35.zza(17);
        zzJ = builder35.withProperty(zzctVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzct zzctVar36 = new zzct();
        zzctVar36.zza(23);
        zzK = builder36.withProperty(zzctVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzct zzctVar37 = new zzct();
        zzctVar37.zza(24);
        zzL = builder37.withProperty(zzctVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzct zzctVar38 = new zzct();
        zzctVar38.zza(25);
        zzM = builder38.withProperty(zzctVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzct zzctVar39 = new zzct();
        zzctVar39.zza(39);
        zzN = builder39.withProperty(zzctVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzct zzctVar40 = new zzct();
        zzctVar40.zza(40);
        zzO = builder40.withProperty(zzctVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzct zzctVar41 = new zzct();
        zzctVar41.zza(30);
        zzP = builder41.withProperty(zzctVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzct zzctVar42 = new zzct();
        zzctVar42.zza(31);
        zzQ = builder42.withProperty(zzctVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzct zzctVar43 = new zzct();
        zzctVar43.zza(32);
        zzR = builder43.withProperty(zzctVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzct zzctVar44 = new zzct();
        zzctVar44.zza(33);
        zzS = builder44.withProperty(zzctVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzct zzctVar45 = new zzct();
        zzctVar45.zza(34);
        zzT = builder45.withProperty(zzctVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzct zzctVar46 = new zzct();
        zzctVar46.zza(35);
        zzU = builder46.withProperty(zzctVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzct zzctVar47 = new zzct();
        zzctVar47.zza(36);
        zzV = builder47.withProperty(zzctVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzct zzctVar48 = new zzct();
        zzctVar48.zza(46);
        zzW = builder48.withProperty(zzctVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzct zzctVar49 = new zzct();
        zzctVar49.zza(47);
        zzX = builder49.withProperty(zzctVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzct zzctVar50 = new zzct();
        zzctVar50.zza(69);
        zzY = builder50.withProperty(zzctVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzct zzctVar51 = new zzct();
        zzctVar51.zza(42);
        zzZ = builder51.withProperty(zzctVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzct zzctVar52 = new zzct();
        zzctVar52.zza(50);
        zzaa = builder52.withProperty(zzctVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzct zzctVar53 = new zzct();
        zzctVar53.zza(51);
        zzab = builder53.withProperty(zzctVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzct zzctVar54 = new zzct();
        zzctVar54.zza(52);
        zzac = builder54.withProperty(zzctVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzct zzctVar55 = new zzct();
        zzctVar55.zza(53);
        zzad = builder55.withProperty(zzctVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzct zzctVar56 = new zzct();
        zzctVar56.zza(54);
        zzae = builder56.withProperty(zzctVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzct zzctVar57 = new zzct();
        zzctVar57.zza(60);
        zzaf = builder57.withProperty(zzctVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzct zzctVar58 = new zzct();
        zzctVar58.zza(85);
        zzag = builder58.withProperty(zzctVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzct zzctVar59 = new zzct();
        zzctVar59.zza(86);
        zzah = builder59.withProperty(zzctVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzct zzctVar60 = new zzct();
        zzctVar60.zza(87);
        zzai = builder60.withProperty(zzctVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzct zzctVar61 = new zzct();
        zzctVar61.zza(55);
        zzaj = builder61.withProperty(zzctVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzct zzctVar62 = new zzct();
        zzctVar62.zza(56);
        zzak = builder62.withProperty(zzctVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzct zzctVar63 = new zzct();
        zzctVar63.zza(57);
        zzal = builder63.withProperty(zzctVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzct zzctVar64 = new zzct();
        zzctVar64.zza(62);
        zzam = builder64.withProperty(zzctVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzct zzctVar65 = new zzct();
        zzctVar65.zza(63);
        zzan = builder65.withProperty(zzctVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzct zzctVar66 = new zzct();
        zzctVar66.zza(64);
        zzao = builder66.withProperty(zzctVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzct zzctVar67 = new zzct();
        zzctVar67.zza(65);
        zzap = builder67.withProperty(zzctVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzct zzctVar68 = new zzct();
        zzctVar68.zza(66);
        zzaq = builder68.withProperty(zzctVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzct zzctVar69 = new zzct();
        zzctVar69.zza(67);
        zzar = builder69.withProperty(zzctVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzct zzctVar70 = new zzct();
        zzctVar70.zza(68);
        zzas = builder70.withProperty(zzctVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzct zzctVar71 = new zzct();
        zzctVar71.zza(70);
        zzat = builder71.withProperty(zzctVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzct zzctVar72 = new zzct();
        zzctVar72.zza(71);
        zzau = builder72.withProperty(zzctVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzct zzctVar73 = new zzct();
        zzctVar73.zza(72);
        zzav = builder73.withProperty(zzctVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzct zzctVar74 = new zzct();
        zzctVar74.zza(73);
        zzaw = builder74.withProperty(zzctVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzct zzctVar75 = new zzct();
        zzctVar75.zza(74);
        zzax = builder75.withProperty(zzctVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzct zzctVar76 = new zzct();
        zzctVar76.zza(75);
        zzay = builder76.withProperty(zzctVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzct zzctVar77 = new zzct();
        zzctVar77.zza(76);
        zzaz = builder77.withProperty(zzctVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzct zzctVar78 = new zzct();
        zzctVar78.zza(77);
        zzaA = builder78.withProperty(zzctVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzct zzctVar79 = new zzct();
        zzctVar79.zza(78);
        zzaB = builder79.withProperty(zzctVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzct zzctVar80 = new zzct();
        zzctVar80.zza(80);
        zzaC = builder80.withProperty(zzctVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzct zzctVar81 = new zzct();
        zzctVar81.zza(81);
        zzaD = builder81.withProperty(zzctVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzct zzctVar82 = new zzct();
        zzctVar82.zza(82);
        zzaE = builder82.withProperty(zzctVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzct zzctVar83 = new zzct();
        zzctVar83.zza(83);
        zzaF = builder83.withProperty(zzctVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzct zzctVar84 = new zzct();
        zzctVar84.zza(84);
        zzaG = builder84.withProperty(zzctVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzct zzctVar85 = new zzct();
        zzctVar85.zza(88);
        zzaH = builder85.withProperty(zzctVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzct zzctVar86 = new zzct();
        zzctVar86.zza(89);
        zzaI = builder86.withProperty(zzctVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzct zzctVar87 = new zzct();
        zzctVar87.zza(90);
        zzaJ = builder87.withProperty(zzctVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzct zzctVar88 = new zzct();
        zzctVar88.zza(91);
        zzaK = builder88.withProperty(zzctVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzct zzctVar89 = new zzct();
        zzctVar89.zza(92);
        zzaL = builder89.withProperty(zzctVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzct zzctVar90 = new zzct();
        zzctVar90.zza(93);
        zzaM = builder90.withProperty(zzctVar90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zzct zzctVar91 = new zzct();
        zzctVar91.zza(94);
        zzaN = builder91.withProperty(zzctVar91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zzct zzctVar92 = new zzct();
        zzctVar92.zza(95);
        zzaO = builder92.withProperty(zzctVar92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zzct zzctVar93 = new zzct();
        zzctVar93.zza(96);
        zzaP = builder93.withProperty(zzctVar93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzct zzctVar94 = new zzct();
        zzctVar94.zza(97);
        zzaQ = builder94.withProperty(zzctVar94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zzct zzctVar95 = new zzct();
        zzctVar95.zza(98);
        zzaR = builder95.withProperty(zzctVar95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zzct zzctVar96 = new zzct();
        zzctVar96.zza(99);
        zzaS = builder96.withProperty(zzctVar96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zzct zzctVar97 = new zzct();
        zzctVar97.zza(100);
        zzaT = builder97.withProperty(zzctVar97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzct zzctVar98 = new zzct();
        zzctVar98.zza(101);
        zzaU = builder98.withProperty(zzctVar98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zzct zzctVar99 = new zzct();
        zzctVar99.zza(102);
        zzaV = builder99.withProperty(zzctVar99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zzct zzctVar100 = new zzct();
        zzctVar100.zza(103);
        zzaW = builder100.withProperty(zzctVar100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zzct zzctVar101 = new zzct();
        zzctVar101.zza(104);
        zzaX = builder101.withProperty(zzctVar101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzct zzctVar102 = new zzct();
        zzctVar102.zza(105);
        zzaY = builder102.withProperty(zzctVar102.zzb()).build();
        FieldDescriptor.Builder builder103 = FieldDescriptor.builder("scannerAutoZoomEvent");
        zzct zzctVar103 = new zzct();
        zzctVar103.zza(106);
        zzaZ = builder103.withProperty(zzctVar103.zzb()).build();
        FieldDescriptor.Builder builder104 = FieldDescriptor.builder("lowLightAutoExposureComputationEvent");
        zzct zzctVar104 = new zzct();
        zzctVar104.zza(107);
        zzba = builder104.withProperty(zzctVar104.zzb()).build();
        FieldDescriptor.Builder builder105 = FieldDescriptor.builder("lowLightFrameProcessEvent");
        zzct zzctVar105 = new zzct();
        zzctVar105.zza(AppCompatDelegate.FEATURE_SUPPORT_ACTION_BAR);
        zzbb = builder105.withProperty(zzctVar105.zzb()).build();
        FieldDescriptor.Builder builder106 = FieldDescriptor.builder("lowLightSceneDetectionEvent");
        zzct zzctVar106 = new zzct();
        zzctVar106.zza(AppCompatDelegate.FEATURE_SUPPORT_ACTION_BAR_OVERLAY);
        zzbc = builder106.withProperty(zzctVar106.zzb()).build();
        FieldDescriptor.Builder builder107 = FieldDescriptor.builder("onDeviceStainRemovalLogEvent");
        zzct zzctVar107 = new zzct();
        zzctVar107.zza(110);
        zzbd = builder107.withProperty(zzctVar107.zzb()).build();
        FieldDescriptor.Builder builder108 = FieldDescriptor.builder("aggregatedOnDeviceStainRemovalLogEvent");
        zzct zzctVar108 = new zzct();
        zzctVar108.zza(111);
        zzbe = builder108.withProperty(zzctVar108.zzb()).build();
        FieldDescriptor.Builder builder109 = FieldDescriptor.builder("stainRemovalOptionalModuleLogEvent");
        zzct zzctVar109 = new zzct();
        zzctVar109.zza(112);
        zzbf = builder109.withProperty(zzctVar109.zzb()).build();
        FieldDescriptor.Builder builder110 = FieldDescriptor.builder("onDeviceShadowRemovalLogEvent");
        zzct zzctVar110 = new zzct();
        zzctVar110.zza(113);
        zzbg = builder110.withProperty(zzctVar110.zzb()).build();
        FieldDescriptor.Builder builder111 = FieldDescriptor.builder("aggregatedOnDeviceShadowRemovalLogEvent");
        zzct zzctVar111 = new zzct();
        zzctVar111.zza(114);
        zzbh = builder111.withProperty(zzctVar111.zzb()).build();
        FieldDescriptor.Builder builder112 = FieldDescriptor.builder("shadowRemovalOptionalModuleLogEvent");
        zzct zzctVar112 = new zzct();
        zzctVar112.zza(115);
        zzbi = builder112.withProperty(zzctVar112.zzb()).build();
        FieldDescriptor.Builder builder113 = FieldDescriptor.builder("onDeviceDigitalInkSegmentationLogEvent");
        zzct zzctVar113 = new zzct();
        zzctVar113.zza(AppInfoTableDecoder.APPLICATION_INFORMATION_TABLE_ID);
        zzbj = builder113.withProperty(zzctVar113.zzb()).build();
        FieldDescriptor.Builder builder114 = FieldDescriptor.builder("onDeviceDocumentScannerStartLogEvent");
        zzct zzctVar114 = new zzct();
        zzctVar114.zza(117);
        zzbk = builder114.withProperty(zzctVar114.zzb()).build();
        FieldDescriptor.Builder builder115 = FieldDescriptor.builder("onDeviceDocumentScannerFinishLogEvent");
        zzct zzctVar115 = new zzct();
        zzctVar115.zza(118);
        zzbl = builder115.withProperty(zzctVar115.zzb()).build();
        FieldDescriptor.Builder builder116 = FieldDescriptor.builder("onDeviceDocumentScannerUiStartLogEvent");
        zzct zzctVar116 = new zzct();
        zzctVar116.zza(119);
        zzbm = builder116.withProperty(zzctVar116.zzb()).build();
        FieldDescriptor.Builder builder117 = FieldDescriptor.builder("onDeviceDocumentScannerUiFinishLogEvent");
        zzct zzctVar117 = new zzct();
        zzctVar117.zza(120);
        zzbn = builder117.withProperty(zzctVar117.zzb()).build();
        FieldDescriptor.Builder builder118 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzct zzctVar118 = new zzct();
        zzctVar118.zza(121);
        zzbo = builder118.withProperty(zzctVar118.zzb()).build();
        FieldDescriptor.Builder builder119 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzct zzctVar119 = new zzct();
        zzctVar119.zza(122);
        zzbp = builder119.withProperty(zzctVar119.zzb()).build();
        FieldDescriptor.Builder builder120 = FieldDescriptor.builder("onDeviceDocumentScannerUiCreateLogEvent");
        zzct zzctVar120 = new zzct();
        zzctVar120.zza(123);
        zzbq = builder120.withProperty(zzctVar120.zzb()).build();
        FieldDescriptor.Builder builder121 = FieldDescriptor.builder("onDeviceSubjectSegmentationCreateLogEvent");
        zzct zzctVar121 = new zzct();
        zzctVar121.zza(124);
        zzbr = builder121.withProperty(zzctVar121.zzb()).build();
        FieldDescriptor.Builder builder122 = FieldDescriptor.builder("onDeviceSubjectSegmentationLoadLogEvent");
        zzct zzctVar122 = new zzct();
        zzctVar122.zza(125);
        zzbs = builder122.withProperty(zzctVar122.zzb()).build();
        FieldDescriptor.Builder builder123 = FieldDescriptor.builder("onDeviceSubjectSegmentationInferenceLogEvent");
        zzct zzctVar123 = new zzct();
        zzctVar123.zza(126);
        zzbt = builder123.withProperty(zzctVar123.zzb()).build();
        FieldDescriptor.Builder builder124 = FieldDescriptor.builder("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzct zzctVar124 = new zzct();
        zzctVar124.zza(WorkQueueKt.MASK);
        zzbu = builder124.withProperty(zzctVar124.zzb()).build();
        FieldDescriptor.Builder builder125 = FieldDescriptor.builder("subjectSegmentationOptionalModuleLogEvent");
        zzct zzctVar125 = new zzct();
        zzctVar125.zza(128);
        zzbv = builder125.withProperty(zzctVar125.zzb()).build();
        FieldDescriptor.Builder builder126 = FieldDescriptor.builder("documentScannerUiModuleScreenViewEvent");
        zzct zzctVar126 = new zzct();
        zzctVar126.zza(TsExtractor.TS_STREAM_TYPE_AC3);
        zzbw = builder126.withProperty(zzctVar126.zzb()).build();
        FieldDescriptor.Builder builder127 = FieldDescriptor.builder("documentScannerUiModuleScreenClickEvent");
        zzct zzctVar127 = new zzct();
        zzctVar127.zza(TsExtractor.TS_STREAM_TYPE_HDMV_DTS);
        zzbx = builder127.withProperty(zzctVar127.zzb()).build();
        FieldDescriptor.Builder builder128 = FieldDescriptor.builder("documentScannerUiModuleScreenErrorEvent");
        zzct zzctVar128 = new zzct();
        zzctVar128.zza(131);
        zzby = builder128.withProperty(zzctVar128.zzb()).build();
    }

    private zzio() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zzoy zzoyVar = (zzoy) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzoyVar.zzf());
        objectEncoderContext2.add(zzc, zzoyVar.zzc());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, zzoyVar.zzb());
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, zzoyVar.zze());
        objectEncoderContext2.add(zzm, zzoyVar.zzd());
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, zzoyVar.zza());
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
        objectEncoderContext2.add(zzaN, (Object) null);
        objectEncoderContext2.add(zzaO, (Object) null);
        objectEncoderContext2.add(zzaP, (Object) null);
        objectEncoderContext2.add(zzaQ, (Object) null);
        objectEncoderContext2.add(zzaR, (Object) null);
        objectEncoderContext2.add(zzaS, (Object) null);
        objectEncoderContext2.add(zzaT, (Object) null);
        objectEncoderContext2.add(zzaU, (Object) null);
        objectEncoderContext2.add(zzaV, (Object) null);
        objectEncoderContext2.add(zzaW, (Object) null);
        objectEncoderContext2.add(zzaX, (Object) null);
        objectEncoderContext2.add(zzaY, (Object) null);
        objectEncoderContext2.add(zzaZ, (Object) null);
        objectEncoderContext2.add(zzba, (Object) null);
        objectEncoderContext2.add(zzbb, (Object) null);
        objectEncoderContext2.add(zzbc, (Object) null);
        objectEncoderContext2.add(zzbd, (Object) null);
        objectEncoderContext2.add(zzbe, (Object) null);
        objectEncoderContext2.add(zzbf, (Object) null);
        objectEncoderContext2.add(zzbg, (Object) null);
        objectEncoderContext2.add(zzbh, (Object) null);
        objectEncoderContext2.add(zzbi, (Object) null);
        objectEncoderContext2.add(zzbj, (Object) null);
        objectEncoderContext2.add(zzbk, (Object) null);
        objectEncoderContext2.add(zzbl, (Object) null);
        objectEncoderContext2.add(zzbm, (Object) null);
        objectEncoderContext2.add(zzbn, (Object) null);
        objectEncoderContext2.add(zzbo, (Object) null);
        objectEncoderContext2.add(zzbp, (Object) null);
        objectEncoderContext2.add(zzbq, (Object) null);
        objectEncoderContext2.add(zzbr, (Object) null);
        objectEncoderContext2.add(zzbs, (Object) null);
        objectEncoderContext2.add(zzbt, (Object) null);
        objectEncoderContext2.add(zzbu, (Object) null);
        objectEncoderContext2.add(zzbv, (Object) null);
        objectEncoderContext2.add(zzbw, (Object) null);
        objectEncoderContext2.add(zzbx, (Object) null);
        objectEncoderContext2.add(zzby, (Object) null);
    }
}
